project:
  key: WEBCOM
  plan:
    name: webcomponent-renovate
    key: WCREN
stages:
  - jobs:
      - scripts:
          - 'docker run --volume ${PWD}/renovate.json:/usr/src/app/renovate.json -e RENOVATE_TOKEN=BAMSCRT@0@0@2sxRkvVzxYftc0x99Xpzh9Hn6BiTsbozp4UgPruwXUBqWhEQawWo2vtac3zphHWV -e RENOVATE_CONFIG_FILE=/usr/src/app/renovate.json -e HTTP_PROXY=http://forwardproxy-pr-build.lb.cumuli.be:3128 -e HTTPS_PROXY=http://forwardproxy-pr-build.lb.cumuli.be:3128 acd-docker.repository.milieuinfo.be/renovate/renovate'
          - /opt/scripts/docker/stop-docker-containers.sh
        requirements:
          - REMOTE_ONLY
