---
version: 2
plan:
  project-key: WEBCO
  key: REN
  name: renovate-bot

stages:
  - Build:
      jobs:
        - Build

Build:
  key: BD
  tasks:
    - clean
    - script: |
          #!/usr/env/bin bash
          set -e
          cp ${bamboo.npmrc_path} .
          docker run --volume ${PWD}/renovate.json:/usr/src/app/renovate.json --volume ${PWD}/.npmrc:/home/ubuntu/.npmrc -e RENOVATE_TOKEN=${bamboo.github_secret_access_token} -e RENOVATE_CONFIG_FILE=/usr/src/app/renovate.json -e HTTP_PROXY=http://forwardproxy-pr-build.lb.cumuli.be:3128 -e HTTPS_PROXY=http://forwardproxy-pr-build.lb.cumuli.be:3128 acd-docker.repository.milieuinfo.be/renovate/renovate
  requirements:
    - REMOTE_ONLY
